import { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { Header } from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  // В случае чего можно добавить тип метаданных; Metadata - позвояет нам сконцетрироваться на next.js
  title: 'Next.js',
  description: 'Generated by Next.js', // description - описание с английского
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container">{children}</main>
        {/* children - это просто главная страница какого либо компонента */}
        {/* Как я помню container - это просто часть страницы с определённой широтой и центральной надписью */}
        <Footer />
      </body>
    </html>
  );
}
